trigger:
- master
pool:
  vmImage: ubuntu-latest
steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
         sudo apt-get install -y bash
         sudo npm install newman --global
         newman run ./demonewpan/postmancollection/Testing.postman_collection.json  --reporters cli,junit --reporter-junit-export junit-report.xml         
         sleep 40
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for postman'
      inputs:
       testResultsFormat: 'JUnit'
       testResultsFiles: '**/*.xml'
       mergeTestResults: true
       failTaskOnFailedTests: false
